# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Russell Morgan
tagline:             My github website
url:                 http://russellmorgan.github.io

#main nav content
pages_list:       
  Home: '/'
  Projects: '/work'
  Blog: '/blog'
  GitHub: 'https://github.com/russellmorgan'
  Resume: '/resume'